### ISSUE TITLE
Mobile Top Page (mock-up)

### ISSUE THREAD

**Issue by chimayh** [yutokyokutyo/choccoco#2]
スマホ用トップページのモックを作成

**Comment by yutokyokutyo** [comment]
this is good issue!!

**Comment by chimayh** [comment]
![mobile-top](https://cloud.githubusercontent.com/assets/2940284/5360008/e0a03afc-8004-11e4-9963-1886da631895.jpg)

Example

**Comment by chimayh** [comment]
横画面になったときどうしよう

**Comment by yutokyokutyo** [comment]
問題だ・・。
例えば今の状態で横画面にするとどうなるんだろう？
あ、これモックか。。

**Comment by yutokyokutyo** [comment]
ちょっと明日にでも社内のデザイナーさんに聞いてみる。。かな。

**Comment by yutokyokutyo** [comment]
参考にしたいショップページ！

http://fructus.jp/

**Comment by yutokyokutyo** [comment]
http://forslagdesign.com/
ここも良いなあ。

**Comment by yutokyokutyo** [comment]
@chimayh 
test

**Comment by yutokyokutyo** [comment]
@yutokyokutyo
test2

**Comment by chimayh** [comment]
2個めのは写真のセンスないとむりや

**Comment by yutokyokutyo** [comment]
test

**Comment by yutokyokutyo** [comment]
test2

**Comment by yutokyokutyo** [comment]
test3
